### ISSUE TITLE
parse error in my image ,but it can be open and show temperature in DJI Thermal Analysis Tool 3

### ISSUE THREAD

**Issue by gewenpulan** [SanNianYiSi/thermal_parser#19]
[DJI_20241216210457_0006_T_航点6.zip](https://github.com/user-attachments/files/18159278/DJI_20241216210457_0006_T_.6.zip)

File "/prog/flask_multigpu copy.py", line 801, in detect_PV_IR_Visible
    temperature = thermal.parse(filepath_image=t_image_path)
  File "/prog/thermal_parser/thermal.py", line 618, in parse
    return self.parse_dirp2(
  File "/prog/thermal_parser/thermal.py", line 823, in parse_dirp2
    assert self._dirp_measure_ex(handle, data_ptr, data_size) == Thermal.DIRP_SUCCESS
AssertionError
[2024-12-17 10:34:04,881] ERROR in app: Exception on /ak007 [POST]
Traceback (most recent call last):
  File "/prog/flask_multigpu copy.py", line 801, in detect_PV_IR_Visible
    temperature = thermal.parse(filepath_image=t_image_path)
  File "/prog/thermal_parser/thermal.py", line 618, in parse
    return self.parse_dirp2(
  File "/prog/thermal_parser/thermal.py", line 823, in parse_dirp2
    assert self._dirp_measure_ex(handle, data_ptr, data_size) == Thermal.DIRP_SUCCESS
AssertionError

During handling of the above exception, another exception occurred:

**Comment by gewenpulan** [comment]
i solve it.    
change  line 604 in  thermal.py   
M3TD  also should be  640x512


            if camera_model != Thermal.DJI_M30T:
                kwargs['image_height'] = int(meta_json['Image Height'])
                kwargs['image_width'] = int(meta_json['Image Width'])

change to 
```
            if camera_model not in [Thermal.DJI_M30T, Thermal.DJI_M3TD]:
                kwargs['image_height'] = int(meta_json['Image Height'])
                kwargs['image_width'] = int(meta_json['Image Width'])
```
